### ISSUE TITLE
meteor dependency issue

### ISSUE THREAD

**Issue by andreGarvin** [renisalcedo/module-essentials#3]
You get not include meteor as a dependency and I am on a windows machine and meteor is a no go on my machine.

```bash
 module-essentials@ start: `meteor run`
```

__error__
```bash
=========================================================================
=======                                                                  
=                                                                        
      =                                                                  
=  Attempting to build bson c++ extension                                
      =                                                                  
=   Windows: no build will be attempted as binaries are prepackaged      
      =                                                                  
=   Unix: on failure the package will still install without the C++ exten
sion  =                                                                  
=                                                                        
      =                                                                  
=========================================================================
=======                                                                  
                                                                         
> fibers@0.6.9 install C:\Users\andre\projects\pg-bin\open-source\module-
essentials\node_modules\fibers                                           
> node ./build.js                                                        
                                                                         
(node:9388) [DEP0006] DeprecationWarning: child_process: options.customFd
s option is deprecated. Use options.stdio instead.                       
events.js:182                                                            
      throw er; // Unhandled 'error' event                               
      ^                                                                  
                                                                         
Error: spawn node-gyp ENOENT                                             
    at _errnoException (util.js:1041:11)                                 
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192
:19)                                                                     
    at onErrorNT (internal/child_process.js:374:16)                      
    at _combinedTickCallback (internal/process/next_tick.js:138:11)      
    at process._tickCallback (internal/process/next_tick.js:180:9)       
    at Function.Module.runMain (module.js:611:11)                        
    at startup (bootstrap_node.js:158:16)                                
    at bootstrap_node.js:598:3                                           
npm ERR! code ELIFECYCLE                                                 
npm ERR! errno 1                                                         
npm ERR! fibers@0.6.9 install: `node ./build.js`                         
npm ERR! Exit status 1                                                   
npm ERR!                                                                 
npm ERR! Failed at the fibers@0.6.9 install script.                      
npm ERR! This is probably not a problem with npm. There is likely additio
nal logging output above.                                                
                                                                         
npm ERR! A complete log of this run can be found in:                     
npm ERR!     C:\Users\andre\AppData\Roaming\npm-cache\_logs\2017-10-26T03
_56_58_619Z-debug.log                                                    
```

**Comment by renisalcedo** [comment]
Hi @andreGarvin. Thank you for your interest in the project!

I will be updating the readme soon to detail the dependencies such as Meteor and MongoDB. In addition, I will be deploying the app on Heroku soon.

PR are WELCOME!!!
